import { FastFood } from "./types";
import { FoodCategoryId } from "./categories";
import { Timestamp } from "firebase/firestore";

const now = Timestamp.now();

export const MOCK_FASTFOODS: FastFood[] = [
  {
    id: "1",
    name: "McDonald's Champs-Élysées",
    chain: "McDonald's",
    category: "smash-burger",
    image_url: "/images/mcdonalds.svg",
    location: { latitude: 48.8698, longitude: 2.3075, address: "140 Av. des Champs-Élysées, 75008 Paris" },
    elo_score: 1580,
    total_matches: 42,
    wins: 28,
    losses: 14,
    created_at: now,
    updated_at: now,
  },
  {
    id: "2",
    name: "Burger King Opéra",
    chain: "Burger King",
    category: "smash-burger",
    image_url: "/images/burgerking.svg",
    location: { latitude: 48.8711, longitude: 2.3316, address: "1 Bd des Italiens, 75009 Paris" },
    elo_score: 1520,
    total_matches: 38,
    wins: 22,
    losses: 16,
    created_at: now,
    updated_at: now,
  },
  {
    id: "3",
    name: "KFC Bastille",
    chain: "KFC",
    category: "poulet-frit",
    image_url: "/images/kfc.svg",
    location: { latitude: 48.8530, longitude: 2.3692, address: "4 Pl. de la Bastille, 75004 Paris" },
    elo_score: 1455,
    total_matches: 35,
    wins: 18,
    losses: 17,
    created_at: now,
    updated_at: now,
  },
  {
    id: "4",
    name: "Five Guys Bercy",
    chain: "Five Guys",
    category: "smash-burger",
    image_url: "/images/fiveguys.svg",
    location: { latitude: 48.8367, longitude: 2.3825, address: "Bercy Village, 75012 Paris" },
    elo_score: 1610,
    total_matches: 30,
    wins: 23,
    losses: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "5",
    name: "Popeyes Grands Boulevards",
    chain: "Popeyes",
    category: "poulet-frit",
    image_url: "/images/popeyes.svg",
    location: { latitude: 48.8714, longitude: 2.3450, address: "32 Bd de Bonne Nouvelle, 75010 Paris" },
    elo_score: 1545,
    total_matches: 25,
    wins: 17,
    losses: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "6",
    name: "Domino's Montmartre",
    chain: "Domino's",
    category: "pizza",
    image_url: "/images/dominos.svg",
    location: { latitude: 48.8867, longitude: 2.3431, address: "18 Rue Lepic, 75018 Paris" },
    elo_score: 1470,
    total_matches: 32,
    wins: 17,
    losses: 15,
    created_at: now,
    updated_at: now,
  },
  {
    id: "7",
    name: "German Döner Kebab République",
    chain: "German Döner Kebab",
    category: "kebab",
    image_url: "/images/kebab.svg",
    location: { latitude: 48.8675, longitude: 2.3636, address: "Pl. de la République, 75003 Paris" },
    elo_score: 1505,
    total_matches: 20,
    wins: 12,
    losses: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "8",
    name: "Pitaya Oberkampf",
    chain: "Pitaya",
    category: "thai",
    image_url: "/images/pitaya.svg",
    location: { latitude: 48.8647, longitude: 2.3783, address: "Rue Oberkampf, 75011 Paris" },
    elo_score: 1530,
    total_matches: 22,
    wins: 14,
    losses: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "9",
    name: "Wok to Walk Châtelet",
    chain: "Wok to Walk",
    category: "asiatique",
    image_url: "/images/woktowalk.svg",
    location: { latitude: 48.8584, longitude: 2.3474, address: "Les Halles, 75001 Paris" },
    elo_score: 1490,
    total_matches: 18,
    wins: 10,
    losses: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "10",
    name: "Pizza Hut Nation",
    chain: "Pizza Hut",
    category: "pizza",
    image_url: "/images/pizzahut.svg",
    location: { latitude: 48.8482, longitude: 2.3893, address: "Pl. de la Nation, 75012 Paris" },
    elo_score: 1420,
    total_matches: 28,
    wins: 12,
    losses: 16,
    created_at: now,
    updated_at: now,
  },
  {
    id: "11",
    name: "Chicking Saint-Michel",
    chain: "Chicking",
    category: "poulet-frit",
    image_url: "/images/chicking.svg",
    location: { latitude: 48.8534, longitude: 2.3443, address: "Bd Saint-Michel, 75005 Paris" },
    elo_score: 1475,
    total_matches: 15,
    wins: 9,
    losses: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "12",
    name: "O'Tacos Gare du Nord",
    chain: "O'Tacos",
    category: "kebab",
    image_url: "/images/otacos.svg",
    location: { latitude: 48.8809, longitude: 2.3553, address: "Gare du Nord, 75010 Paris" },
    elo_score: 1440,
    total_matches: 26,
    wins: 13,
    losses: 13,
    created_at: now,
    updated_at: now,
  },
];

export function getRandomDuel(fastfoods: FastFood[], category?: FoodCategoryId): [FastFood, FastFood] {
  const pool = category && category !== "all"
    ? fastfoods.filter((ff) => ff.category === category)
    : fastfoods;
  const list = pool.length >= 2 ? pool : fastfoods;
  const shuffled = [...list].sort(() => Math.random() - 0.5);
  return [shuffled[0], shuffled[1]];
}
